In [1]:
# 测试 4 比特 Heisenberg 模型在不同的对称性变化基矢量下的哈密顿矩阵构造，以及本真值 
#
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d
import numpy as np # generic math functions

In [2]:
# 构造 XXZ 哈密顿量
# define operators with OBC using site-coupling lists
L = 4
Jxy = np.sqrt(1.0) # xy interaction
Jzz_0 = 1.0 # zz interactiion
hz = 0 # z external field
J_zz = [[Jzz_0, i, i+1] for i in range(L-1)] # OBC
J_xy = [[Jxy/2.0, i, i+1] for i in range(L-1)] # OBC
h_z = [[hz, i] for i in range(L-1)]
# static and dynamic lists
static = [["+-", J_xy], ["-+", J_xy], ["zz", J_zz], ["z", h_z]]
dynamic = []

In [3]:
# 构造不同对称性的基矢量
# 不加对称性的基矢量
basis = spin_basis_1d(L)
print("basis:\n", basis)
H = hamiltonian(static,dynamic,basis=basis,dtype = np.float64)
print('nonzero-elements in Hamiltonian:\n', H.H)
print(print('the eigen values of Hamiltonian', H.eigvalsh()))

basis:
 reference states: 
array index   /   Fock state   /   integer repr. 
      0.         |1 1 1 1>           15  
      1.         |1 1 1 0>           14  
      2.         |1 1 0 1>           13  
      3.         |1 1 0 0>           12  
      4.         |1 0 1 1>           11  
      5.         |1 0 1 0>           10  
      6.         |1 0 0 1>            9  
      7.         |1 0 0 0>            8  
      8.         |0 1 1 1>            7  
      9.         |0 1 1 0>            6  
     10.         |0 1 0 1>            5  
     11.         |0 1 0 0>            4  
     12.         |0 0 1 1>            3  
     13.         |0 0 1 0>            2  
     14.         |0 0 0 1>            1  
     15.         |0 0 0 0>            0  
Hermiticity check passed!


C:\Users\admin\AppData\Local\Temp\ipykernel_18000\3147131484.py:5: UserWarning: Test for symmetries not implemented for <class 'quspin.basis.basis_1d.spin.spin_basis_1d'>, to turn off this warning set check_symm=False in hamiltonian
  H = hamiltonian(static,dynamic,basis=basis,dtype = np.float64)


nonzero-elements in Hamiltonian:
 static mat: 
  (0, 0)	3.0
  (1, 1)	1.0
  (1, 2)	2.0
  (2, 1)	2.0
  (2, 2)	-1.0
  (2, 4)	2.0
  (3, 3)	1.0
  (3, 5)	2.0
  (4, 2)	2.0
  (4, 4)	-1.0
  (4, 8)	2.0
  (5, 3)	2.0
  (5, 5)	-3.0
  (5, 6)	2.0
  (5, 9)	2.0
  (6, 5)	2.0
  (6, 6)	-1.0
  (6, 10)	2.0
  (7, 7)	1.0
  (7, 11)	2.0
  (8, 4)	2.0
  (8, 8)	1.0
  (9, 5)	2.0
  (9, 9)	-1.0
  (9, 10)	2.0
  (10, 6)	2.0
  (10, 9)	2.0
  (10, 10)	-3.0
  (10, 12)	2.0
  (11, 7)	2.0
  (11, 11)	-1.0
  (11, 13)	2.0
  (12, 10)	2.0
  (12, 12)	1.0
  (13, 11)	2.0
  (13, 13)	-1.0
  (13, 14)	2.0
  (14, 13)	2.0
  (14, 14)	1.0
  (15, 15)	3.0


dynamic:

the eigen values of Hamiltonian [-6.46410162 -3.82842712 -3.82842712 -3.82842712 -1.         -1.
 -1.          0.46410162  1.82842712  1.82842712  1.82842712  3.
  3.          3.          3.          3.        ]
None


In [10]:
# 在 Sz = 0 的子空间
basis = spin_basis_1d(L, Nup= L // 2)
print("basis:\n", basis)
H = hamiltonian(static,dynamic,basis=basis,dtype = np.float64)
print('nonzero-elements in Hamiltonian:\n', H.H)
print('transfer to array:\n',H.H().toarray())
print(print('the eigen values of Hamiltonian', H.eigvalsh()))


basis:
 reference states: 
array index   /   Fock state   /   integer repr. 
     0.         |1 1 0 0>           12  
     1.         |1 0 1 0>           10  
     2.         |1 0 0 1>            9  
     3.         |0 1 1 0>            6  
     4.         |0 1 0 1>            5  
     5.         |0 0 1 1>            3  
Hermiticity check passed!
Particle conservation check passed!
nonzero-elements in Hamiltonian:
 static mat: 
  (0, 0)	1.0
  (0, 1)	2.0
  (1, 0)	2.0
  (1, 1)	-3.0
  (1, 2)	2.0
  (1, 3)	2.0
  (2, 1)	2.0
  (2, 2)	-1.0
  (2, 4)	2.0
  (3, 1)	2.0
  (3, 3)	-1.0
  (3, 4)	2.0
  (4, 2)	2.0
  (4, 3)	2.0
  (4, 4)	-3.0
  (4, 5)	2.0
  (5, 4)	2.0
  (5, 5)	1.0


dynamic:

transfer to array:
 [[ 1.  2.  0.  0.  0.  0.]
 [ 2. -3.  2.  2.  0.  0.]
 [ 0.  2. -1.  0.  2.  0.]
 [ 0.  2.  0. -1.  2.  0.]
 [ 0.  0.  2.  2. -3.  2.]
 [ 0.  0.  0.  0.  2.  1.]]
the eigen values of Hamiltonian [-6.46410162 -3.82842712 -1.          0.46410162  1.82842712  3.        ]
None


C:\Users\admin\AppData\Local\Temp\ipykernel_18000\3383665063.py:4: UserWarning: Test for symmetries not implemented for <class 'quspin.basis.basis_1d.spin.spin_basis_1d'>, to turn off this warning set check_symm=False in hamiltonian
  H = hamiltonian(static,dynamic,basis=basis,dtype = np.float64)


In [11]:
print('transfer to array:\n',H.H().toarray())

transfer to array:
 [[ 1.  2.  0.  0.  0.  0.]
 [ 2. -3.  2.  2.  0.  0.]
 [ 0.  2. -1.  0.  2.  0.]
 [ 0.  2.  0. -1.  2.  0.]
 [ 0.  0.  2.  2. -3.  2.]
 [ 0.  0.  0.  0.  2.  1.]]


In [12]:
# 在 Sz = 0 的子空间
# 同时加上 zblock = 1 的 symmetry (spin inversion symmetry)
basis = spin_basis_1d(L, Nup= L // 2, zblock = 1)
print("basis:\n", basis)
H = hamiltonian(static,dynamic,basis=basis,dtype = np.float64)
print('nonzero-elements in Hamiltonian:\n', H.H)
print('transfer to array:\n',H.H().toarray())
print(print('the eigen values of Hamiltonian', H.eigvalsh()))

basis:
 reference states: 
array index   /   Fock state   /   integer repr. 
     0.         |1 1 0 0>           12  
     1.         |1 0 1 0>           10  
     2.         |1 0 0 1>            9  
The states printed do NOT correspond to the physical states: see review arXiv:1101.3281 for more details about reference states for symmetry-reduced blocks.

Hermiticity check passed!
Particle conservation check passed!
nonzero-elements in Hamiltonian:
 static mat: 
  (0, 0)	1.0
  (0, 1)	2.0
  (1, 0)	2.0
  (1, 1)	-3.0
  (1, 2)	4.0
  (2, 1)	4.0
  (2, 2)	-1.0


dynamic:

transfer to array:
 [[ 1.  2.  0.]
 [ 2. -3.  4.]
 [ 0.  4. -1.]]
the eigen values of Hamiltonian [-6.46410162  0.46410162  3.        ]
None


C:\Users\admin\AppData\Local\Temp\ipykernel_18000\1270287355.py:5: UserWarning: Test for symmetries not implemented for <class 'quspin.basis.basis_1d.spin.spin_basis_1d'>, to turn off this warning set check_symm=False in hamiltonian
  H = hamiltonian(static,dynamic,basis=basis,dtype = np.float64)


In [13]:
print('transfer to array:\n',H.H().toarray())

transfer to array:
 [[ 1.  2.  0.]
 [ 2. -3.  4.]
 [ 0.  4. -1.]]
